import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useContext } from 'react'
import { useEffect } from 'react'
import { ToastContainer } from 'react-toastify'
import { Store } from '../utils/Store'
import { signOut, useSession } from 'next-auth/react'
import 'react-toastify/dist/ReactToastify.css'
import {Menu} from '@headlessui/react'
import DropdownLink from './DropdownLink'
import Cookies from 'js-cookie'

function Layout({children,title}) {
    const {status,data:session}=useSession()

    const {state,dispatch} = useContext(Store)
    const [cartItemCount, setCartItemCount] = useState(0)

    useEffect(()=>{
        setCartItemCount(state.cart.cartItems.reduce((a,c)=>a+c.quantity,0))
    },[cartItemCount, state.cart.cartItems])

    const logOutHandler=()=>{
        Cookies.remove('cart')
        dispatch({type:'CART_RESET'})
        signOut({callbackUrl:'/login'})
    }
  return (
    <>
    <Head>
        <title>{title? title+" -Green'":"green'Com"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position='bottom-center' limit={1} />
    <div className='flex min-h-screen flex-col justify-between'>
        <header>
            <nav className='flex h-12 items-center px-4 justify-between shadow-md '>
                <Link href='/' legacyBehavior>
                    <a href="" className='text-lg font-bold'>{"Green'"} Comm</a>
                </Link>
                <div>
                    <Link className='p-2' href='/cart'> Cart
                    {cartItemCount>0 &&(
                        <span className='ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white'>
                            {cartItemCount}
                        </span>
                    )}
                    </Link>
                    {
                        status==='loading'?(
                            'Loading'
                            ):(
                            session?.user ?(
                                 <Menu as='div' className='relative inline-block'>
                                    <Menu.Button className='text-blue-600'>
                                        {session.user.name}
                                    </Menu.Button>
                                    <Menu.Items className='absolute right-0 w-56 origin-top-right bg-white  shadow-lg'>
                                        <Menu.Item>
                                            <DropdownLink className="dopdawn-link" href='/profile'>
                                                Profile
                                            </DropdownLink>
                                        </Menu.Item>
                                        <Menu.Item>
                                            <DropdownLink 
                                            className="dopdawn-link" 
                                            href='/order-history'>
                                                Order History
                                            </DropdownLink>
                                        </Menu.Item>
                                        <Menu.Item>
                                            <a href="#" className="dopdawn-link"
                                            onClick={logOutHandler}
                                            >
                                                Logout
                                            </a>
                                        </Menu.Item>
                                    </Menu.Items>
                                 </Menu>
                                 ):(
                                <Link href='/login'>
                                    Login
                                </Link>
                            )
                        )
                    }
                </div>
            </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>
            {children}
        </main>
        <footer className='flex h-10 justify-center items-center shadow-inner'>
            copyright GreenVarch @2022
        </footer>
    </div>
    </>
  )
}

export default Layout
